services:
  depthai_node:
    image: "luxonis/depthai-ros:${SW9_ARCH:-kilted-latest}"
    network_mode: "host"
    privileged: true
    runtime: nvidia
    restart: always
    environment:
      - ROS_DOMAIN_ID=0
      - FASTDDS_DEFAULT_PROFILES_FILE=/root/ROS/fastdds_no_shm.xml
    healthcheck:
      test: 
        - "CMD-SHELL"
        - |
          /bin/bash -c "export FASTDDS_DEFAULT_PROFILES_FILE=/root/ROS/fastdds_no_shm.xml && \
          source /opt/ros/kilted/setup.bash && \
          ros2 topic echo --once /camera/camera/color/camera_info"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 120s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/bash", "-c", "/root/ROS/depthai-entrypoint.sh"]
    working_dir: /root/ROS
    user: root
    volumes:
      - ${SW9_DOCKER_WORKING_DIR}:/root/ROS
      - /dev:/dev

  yolo_ros:
    build:
      context: ${SW9_DOCKER_WORKING_DIR}/yolo-ros
      dockerfile: Dockerfile
    image: "yolo_ros:latest"
    network_mode: "host"
    privileged: true
    runtime: nvidia
    restart: always
    environment:
      - ROS_DOMAIN_ID=0
      - FASTDDS_DEFAULT_PROFILES_FILE=/root/ROS/fastdds_no_shm.xml
    depends_on:
      depthai_node:
        condition: service_healthy
    healthcheck:
      test: 
        - "CMD-SHELL"
        - |
          /bin/bash -c "export FASTDDS_DEFAULT_PROFILES_FILE=/root/ROS/fastdds_no_shm.xml && \
          source /opt/ros/kilted/setup.bash && \
          ros2 topic echo --once /yolo/dbg_image"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/bash", "-c", "/root/ROS/yolo-entrypoint.sh"]
    working_dir: /root/ROS
    user: root
    volumes:
      - ${SW9_DOCKER_WORKING_DIR}:/root/ROS
      - /dev:/dev
